SELECT F_NAME,L_NAME from EMPLOYEES where ADDRESS LIKE '%Elgin,IL%';

SELECT F_NAME,L_NAME from EMPLOYEES where B_DATE  LIKE '197%';

SELECT F_NAME,L_NAME from EMPLOYEES where DEP_ID = 5   AND SALARY >=60000 and SALARY<=70000;

SELECT * FROM EMPLOYEES ORDER BY DEP_ID;

SELECT L_NAME,DEP_ID FROM EMPLOYEES ORDER BY DEP_ID  DESC;  

SELECT  DEP_ID ,COUNT(*) FROM EMPLOYEES GROUP BY DEP_ID;

SELECT  DEP_ID ,COUNT(*),AVG(SALARY) FROM EMPLOYEES GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
FROM EMPLOYEES
GROUP BY DEP_ID
ORDER BY AVG_SALARY;

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY"
FROM EMPLOYEES
GROUP BY DEP_ID
HAVING COUNT(*) < 4
